### ISSUE TITLE
Failed to send request to Resource server with JWT Token

### ISSUE THREAD

**Issue by huhuhong** [dynamind/spring-boot-security-oauth2-minimal#1]
I'm trying to use a trusted client example with Password Grant Type and i was able to receive the JWT Token. 

Question now is how should use the JWT token to send request to Resource App.

I had tried to use details.tokenValue as Bearer token but some such 

Resource Request, highlighted is the JWT Token
![image](https://cloud.githubusercontent.com/assets/4309039/11241028/3bf293aa-8e32-11e5-984a-4f75fa6bacf0.png)

In OAuthApp

``` java
                            // Trusted client: similar to confidential client but also allowed to handle user password
                    .withClient("trusted").secret("secret")
                    .authorities("ROLE_TRUSTED_CLIENT")
                    .authorizedGrantTypes("client_credentials", "password", "authorization_code", "refresh_token")
                    .scopes("read", "write")
                    .redirectUris("http://localhost:8080/client/")
```

In Client app

``` yml
config:
    oauth2:
        clientID: trusted --default is confidential 
        clientSecret: secret
```

**Comment by dynamind** [comment]
In Postman you should select `OAuth 2.0` instead of `Basic Auth`. Bearer is not a username.
You can also manually add a HTTP header `Authorization` with value `Bearer <access-token>` on the Headers tab.
