### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mrcrch** [dynamind/spring-boot-security-oauth2-minimal#4]
Hello! First of all thanks for sharing your job.

I'd like to use your project as starting point for an academic project that will be licensed under MIT License.

My concern is that your code doesn't define a license, so I'm assuming that's copyrighted.

Could you enlighten that, please?

Thanks in advance

**Comment by dynamind** [comment]
MIT is fine, go ahead. This is just a toy.

**Comment by mrcrch** [comment]
Thanks!
