### ISSUE TITLE
Is authorization server must be STATE?

### ISSUE THREAD

**Issue by liuyatao** [dynamind/spring-boot-security-oauth2-minimal#5]
Hi,Firstly thanks for your demo code which let me understand OAuth 2.0 clearly.But what makes confused is whether the authorization should be a STATE app.

I have a STATELESS web application(Actually It is generated by Jhipster).The config code is [here](https://github.com/jhipster/jhipster-sample-app-oauth2/blob/master/src/main/java/io/github/jhipster/sample/config/SecurityConfiguration.java).The app is already configured as a OAuth Server,and the code is [here](https://github.com/jhipster/jhipster-sample-app-oauth2/blob/master/src/main/java/io/github/jhipster/sample/config/OAuth2ServerConfiguration.java). 

When I used a Client to get the access token,It doesn't to redirect to the login page.It just to appear dialog from chrome to input the username and password.If the username and password is matched, the Client can call the resource server's api.

What I want to achieve is chrome can redirect to he authorization server login page  when I use a client to get a access token .Is it can achieved?

Thanks for you code ,and thanks for your reading my poor English question.If it is convenient,you can contact me by email:739697044@qq.com

**Comment by dynamind** [comment]
Hello, I just came back from vacation, but I'll have a look at your question soon.

**Comment by dynamind** [comment]
I suspect you have Http Basic security enabled, on top of OAuth. Disable it, and see if it redirects. 

I talk about it here: https://github.com/dynamind/spring-boot-security-oauth2-minimal/tree/master/client

> We're using the client part of the Spring Security OAuth 2.0 framework. Since the framework depends on Spring Security, it is dragged in as a transitive dependency. Spring Boot auto-configuration notices this, which then locks down your entire application with a random password.
> 
> That's not what we want.
> 
> We just want to access an OAuth 2.0 protected resource, and use the login form of the authorization server. Luckily, there's a simple solution to this. Just set security.basic.enabled to false in application.yml. This simply tells Spring Boot auto-configuration (specifically SpringBootWebSecurityConfiguration) to setup a request matcher which always returns false - effectively disabling security.

You also ask: Does the authorization server need to be stateful?

In a minimal scenario, only the client has to hold state (the token). 
The resource server does not need state, and while the authorization server may require temporary state depending on the grant type, you can offload that state to a database.

To be more specific:

Most grant types don't require the authorization server to remember state: password grant, client credentials grant, implicit grant. The authorization code flow requires temporary state; the authorization server generates an authorization code it needs to remember long enough for the client to exchange it for a token. This authorization code can also be stored in the database, so you can have one instance of the authorization server generate an authorization code, and have another instance exchange it for a token.

I hope this helps!
